--- #YAML:1.0
name:         SystemC-Vregs
version:      1.464
version_from: Vregs.pm
abstract:     Extract C++/Verilog Enum and Classes from html documents
license:      perl
installdirs:  site
author:
    - Wilson Snyder <wsnyder@wsnyder.org>
resources:
    homepage: http://www.veripool.org/vregs
    bugtracker: http://www.veripool.org/vregs-bugs
requires:
    Bit::Vector:                   0
    HTML::Parser:                  0
    HTML::TableExtract:            0
    Pod::Usage:                    1.34
    Verilog::Language:             2.1

meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
distribution_type: module
generated_by: hand
